import { lazy, useEffect, useState } from "react";
import { attachSessionTerminal, focusSessionPane, getSessionTerminalUrl } from "../../api";
import { AdoptDialog } from "../AdoptDialog";
import { CloseSessionDialog } from "../CloseSessionDialog";
import type { TmuxDiagnostic, TmuxSessionInfo } from "../../types";

const PaneViewer = typeof window === "undefined"
  ? ({ className = "" }: { session: string; paneId: string; kind: "managed" | "foreign"; className?: string }) => <div className={className} data-testid="pane-view-fallback" />
  : lazy(async () => ({ default: (await import("../PaneViewer")).PaneViewer }));

/**
 * Pane que debe quedar seleccionado tras una actualización del inventario: el vigente si sigue
 * existiendo, y si no el primero. Los ids de pane de tmux (%N) son únicos por servidor, así que
 * un id que no aparece en la lista nueva es un pane que se fue (o una sesión distinta).
 */
export function nextSelectedPane(current: string | null, panes: readonly { id: string }[]): string | null {
  return current && panes.some((pane) => pane.id === current) ? current : panes[0]?.id ?? null;
}

export function SessionWorkspace({ session, diagnostic, terminalGrid = false, terminalUrl: initialTerminalUrl, onRefresh, onNew, inspectorVisible, onToggleInspector }: { session: TmuxSessionInfo | null; diagnostic: TmuxDiagnostic | null; terminalGrid?: boolean; terminalUrl?: string | null; onRefresh: () => Promise<void>; onNew: () => void; inspectorVisible?: boolean; onToggleInspector?: () => void }) {
  const [pane, setPane] = useState<string | null>(null); const [adopting, setAdopting] = useState(false); const [terminalUrl, setTerminalUrl] = useState<string | null>(initialTerminalUrl ?? null); const [terminalError, setTerminalError] = useState<string | null>(null); const [terminalLoading, setTerminalLoading] = useState(Boolean(session) && initialTerminalUrl === undefined); const [terminalSession, setTerminalSession] = useState<string | null>(initialTerminalUrl === undefined ? null : session?.name ?? null); const [attachError, setAttachError] = useState<string | null>(null); const [closing, setClosing] = useState(false);
  // El inventario se resondea cada 5s y `session.panes` llega como un array NUEVO aunque nada
  // haya cambiado. Resetear a `panes[0]` en cada llegada le quitaba al operador el pane que
  // acababa de elegir: por eso la decisión es una función pura sobre el pane vigente, y la
  // dependencia es la LISTA de ids (string estable), no la identidad del array.
  const paneIds = session?.panes.map((item) => item.id).join(",") ?? "";
  useEffect(() => setPane((current) => nextSelectedPane(current, session?.panes ?? [])), [session?.name, paneIds]);
  useEffect(() => { if (initialTerminalUrl !== undefined) { setTerminalUrl(initialTerminalUrl); setTerminalLoading(false); setTerminalSession(session?.name ?? null); return; } let alive = true; setTerminalUrl(null); setTerminalError(null); setTerminalLoading(Boolean(session)); setTerminalSession(null); setAttachError(null); setClosing(false); if (!session) return () => { alive = false; }; void getSessionTerminalUrl(session.name).then((result) => { if (alive) { setTerminalUrl(result.url); setTerminalError(result.error); setTerminalLoading(false); setTerminalSession(session.name); } }).catch((error) => { if (alive) { setTerminalError((error as Error).message); setTerminalLoading(false); setTerminalSession(session.name); } }); return () => { alive = false; }; }, [session?.name, initialTerminalUrl]);
  if (diagnostic) return <div className="ronin-empty-workspace"><span>tmux inaccesible</span><h1>{diagnostic.code}</h1><p>{diagnostic.detail}</p><button className="n-btn n-btn-secondary" onClick={() => void onRefresh()}>Reintentar</button></div>;
  if (!session) return <div className="ronin-empty-workspace"><span>tmux</span><h1>Sin sesión seleccionada</h1><p>Crea una sesión gestionada o selecciona una sesión activa de tmux.</p><button className="n-btn n-btn-primary" onClick={onNew}>Nueva sesión</button></div>;
  // A state update from the previous selected session is visible for one render before this
  // effect runs. Never mount xterm's fallback from that stale terminal resolution.
  const terminalPending = initialTerminalUrl === undefined && (terminalLoading || terminalSession !== session.name);
  const selectedPane = session.panes.find((item) => item.id === pane) ?? session.panes[0] ?? null;
  if (terminalGrid) return <div className="ronin-terminals"><header className="ronin-view-header"><div><h1>Terminales</h1><p>{session.name} · {session.panes.length} panes · {terminalUrl ? "tmux en vivo (ttyd)" : "snapshots tmux"}</p></div><div className="ronin-header-actions"><InspectorToggle visible={inspectorVisible} onToggle={onToggleInspector} /><button className="n-btn n-btn-secondary" onClick={() => void onRefresh()}>Sincronizar</button></div></header>{terminalPending ? <p className="ronin-terminal-note">conectando terminal…</p> : terminalUrl ? <iframe key={`grid-${session.name}`} className="ttyd ronin-session-ttyd" src={terminalUrl} title="terminales" /> : <div className="ronin-terminal-grid" data-testid="tmux-pane-grid">{session.panes.map((item) => <section className="ronin-terminal-cell" key={item.id}><header><code>{item.id} · win {item.windowIndex}</code><span>{item.role ?? item.command ?? "shell"}</span></header><PaneViewer session={session.name} paneId={item.id} kind={session.kind} className="ronin-pane-view" /></section>)}</div>}</div>;
  const fallback = selectedPane ? <PaneViewer session={session.name} paneId={selectedPane.id} kind={session.kind} className="ronin-pane-view" /> : <p>No hay un pane para abrir.</p>;
  const terminal = terminalPending ? <p>conectando terminal…</p> : terminalUrl ? <iframe key={session.name} className="ttyd ronin-session-ttyd" src={terminalUrl} title="terminal" /> : <>{terminalError && <p className="ronin-form-error">{terminalError}</p>}<header><code>{selectedPane?.id} {selectedPane?.command}</code><span>respaldo de sólo lectura</span></header>{fallback}</>;
  return <div className="ronin-session-workspace"><header className="ronin-view-header"><div><div className="ronin-heading-line"><h1>{session.presentation?.title || session.name}</h1><span className={`tag ${session.kind === "managed" ? "tag-accent" : "tag-neutral"}`}>{session.kind === "managed" ? "gestionada" : "ajena a Ronin"}</span></div><p><code>{session.name} · {session.panes.length} panes</code></p></div><div className="ronin-header-actions">{session.kind === "foreign" && <button className="n-btn n-btn-primary" onClick={() => setAdopting(true)}>Adoptar</button>}<button className="n-btn n-btn-secondary" data-testid="attach-session" onClick={() => void attachSessionTerminal(session.name).then(() => setAttachError(null)).catch((error) => setAttachError((error as Error).message))}>Attach</button><button className="n-btn n-btn-danger" data-testid="close-session" onClick={() => setClosing(true)}>Cerrar sesión</button><button className="n-btn n-btn-secondary" onClick={() => void onRefresh()}>↻</button><InspectorToggle visible={inspectorVisible} onToggle={onToggleInspector} /></div></header>{attachError && <p className="ronin-form-error">{attachError}</p>}<div className="ronin-session-body"><div className="ronin-pane-list">{session.panes.map((item) => <button className={selectedPane?.id === item.id ? "chosen" : ""} key={item.id} onClick={() => { setPane(item.id); if (session.kind === "managed") void focusSessionPane(session.name, item.id).then((e) => setAttachError(e ? e.error : null)); }}><code>{item.id}</code><span>{item.role ?? (item.command || "shell")}</span><small>win {item.windowIndex}</small></button>)}</div><section className="ronin-terminal-stage">{terminal}</section></div>{adopting && <AdoptDialog session={session} onCancel={() => setAdopting(false)} onAdopted={() => { setAdopting(false); void onRefresh(); }} />}{closing && <CloseSessionDialog session={session} onCancel={() => setClosing(false)} onClosed={() => { setClosing(false); void onRefresh(); }} />}</div>;
}

function InspectorToggle({ visible = true, onToggle }: { visible?: boolean; onToggle?: () => void }) { return <button className="n-btn n-btn-secondary" data-testid="inspector-toggle" aria-controls="ronin-inspector" aria-expanded={visible} title={visible ? "Ocultar inspector" : "Mostrar inspector"} onClick={onToggle}>Inspector</button>; }
export function SessionInspector({ session, diagnostic }: { session: TmuxSessionInfo | null; diagnostic: TmuxDiagnostic | null }) { const request = session?.request && (session.request.length > 300 ? `${session.request.slice(0, 300)}…` : session.request); const attention = session?.attention; const waiting = attention?.since === undefined ? null : Math.max(0, Math.floor((Date.now() - attention.since) / 60_000)); return <div className="ronin-inspector-inner"><span className="ronin-eyebrow">inspector</span><h2>{diagnostic ? "Estado de tmux" : session?.presentation?.title || session?.name || "Sin selección"}</h2>{diagnostic ? <><span className="ronin-inspector-status fail">● {diagnostic.code}</span><p>{diagnostic.detail}</p></> : session ? <><span className={`ronin-inspector-status ${session.kind}`}>◆ {session.kind === "managed" ? "Gestionada" : "Ajena"}</span><dl><dt>tmux</dt><dd>{session.name}</dd><dt>Repo</dt><dd>{session.presentation?.repo ?? "—"}</dd>{request && <><dt>Petición</dt><dd>{request}</dd></>}{attention && <><dt>Estado</dt><dd>{attention.level}{attention.question ? ` · ${attention.question}` : ""}{attention.paneId ? ` · ${attention.paneId}` : ""}{waiting !== null ? ` · esperando hace ${waiting}m` : ""}</dd></>}<dt>Ventanas</dt><dd>{session.windows}</dd><dt>Panes</dt><dd>{session.panes.length}</dd></dl></> : <p>Selecciona una sesión de la lista lateral.</p>}</div>; }
