import { useCallback, useEffect, useRef, useState } from "react";
import { acceptWorkflowProposal, analyzeWorkflows, createWorkflow, deleteWorkflow, dismissWorkflowProposal, getWorkflowAnalysis, getWorkflowCatalog, getWorkflowProposals, updateWorkflow, WorkflowSaveError } from "../../api";
import { ProposalList } from "../ProposalList";
import { StageEditor } from "../StageEditor";
import { StageModal } from "../StageModal";
import { WorkflowGraph } from "../WorkflowGraph";
import { WorkflowJsonEditor } from "../WorkflowJsonEditor";
import { adoptServerConfig, cancel, createWorkflowWorkspaceDraft, insertStageAt, setJsonText, setStages, switchView, type DraftView, type WorkflowDraftState } from "../workflow-draft";
import type { WorkflowAnalysis, WorkflowCatalogItem, WorkflowConfig, WorkflowProposal } from "../../types";

export const NEW_WORKFLOW_TEMPLATE: WorkflowConfig = { stages: [{ key: "planning", label: "Plan", icon: "📋" }, { key: "implementing", label: "Impl", icon: "⌨️", role: "impl" }, { key: "tests", label: "Tests", icon: "🧪" }], verifyAfter: null };
export const isoDay = (offsetDays = 0) => new Date(Date.now() + offsetDays * 86_400_000).toISOString().slice(0, 10);
export interface WorkflowInsights { analysis: WorkflowAnalysis | null; proposals: WorkflowProposal[]; busy: boolean; error: string | null; start: (range: { from?: string; to?: string }) => Promise<void>; accept: (id: string) => Promise<string | null>; dismiss: (id: string) => Promise<void>; refresh: () => Promise<void>; }
export function useWorkflowInsights(): WorkflowInsights {
  const [analysis, setAnalysis] = useState<WorkflowAnalysis | null>(null); const [proposals, setProposals] = useState<WorkflowProposal[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const poll = useRef<number>();
  const refresh = useCallback(async () => setProposals(await getWorkflowProposals("proposed")), []); useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => { const id = analysis?.id; if (!id || analysis.status !== "running") return; let alive = true; const tick = async () => { const next = await getWorkflowAnalysis(id); if (!alive) return; if (next) setAnalysis(next); if (!next || next.status === "running") { poll.current = window.setTimeout(tick, 3000); return; } if (next.status === "done") await refresh(); }; poll.current = window.setTimeout(tick, 3000); return () => { alive = false; window.clearTimeout(poll.current); }; }, [analysis?.id, analysis?.status, refresh]);
  const start = useCallback(async (range: { from?: string; to?: string }) => { setBusy(true); setError(null); try { const { analysisId } = await analyzeWorkflows(range); setAnalysis(await getWorkflowAnalysis(analysisId) ?? { id: analysisId, from: range.from ?? "", to: range.to ?? "", status: "running", createdAt: new Date().toISOString(), proposalIds: [], discarded: [], signals: { tasks: 0, commits: 0, evidenceFiles: 0 } }); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }, []);
  const accept = useCallback(async (id: string) => { setBusy(true); try { const created = await acceptWorkflowProposal(id); setProposals((list) => list.filter((item) => item.id !== id)); return created.id; } catch (e) { setError((e as Error).message); return null; } finally { setBusy(false); } }, []);
  const dismiss = useCallback(async (id: string) => { setBusy(true); try { await dismissWorkflowProposal(id); setProposals((list) => list.filter((item) => item.id !== id)); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }, []);
  return { analysis, proposals, busy, error, start, accept, dismiss, refresh };
}
export function WorkflowContext() { return <div className="ronin-context-head"><span className="ronin-eyebrow">workflows</span><h2>Loops guardados</h2><p className="ronin-context-copy">Grafo, stepper y JSON editan el mismo workflow.</p></div>; }
export function WorkflowWorkspace({ insights, selectId, onLaunch, initialCatalog }: { insights?: WorkflowInsights; selectId?: string; onLaunch: () => void; initialCatalog?: WorkflowCatalogItem[] }) {
  const [catalog, setCatalog] = useState<WorkflowCatalogItem[]>(initialCatalog ?? []); const [id, setId] = useState(initialCatalog?.[0]?.id ?? ""); const [draft, setDraft] = useState<WorkflowDraftState | null>(initialCatalog?.[0] ? createWorkflowWorkspaceDraft(initialCatalog[0].config) : null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); const [creating, setCreating] = useState(false); const [deleting, setDeleting] = useState(false); const [editingStage, setEditingStage] = useState<number | null>(null); const [newName, setNewName] = useState(""); const [rangeOpen, setRangeOpen] = useState(false); const [from, setFrom] = useState(() => isoDay(-14)); const [to, setTo] = useState(() => isoDay());
  useEffect(() => { if (!initialCatalog) void getWorkflowCatalog().then((r) => { const items = r?.items ?? []; setCatalog(items); setId(items[0]?.id ?? ""); }); }, [initialCatalog]);
  useEffect(() => { if (!selectId) return; void getWorkflowCatalog().then((r) => { const items = r?.items ?? []; setCatalog(items); if (items.some((x) => x.id === selectId)) setId(selectId); }); }, [selectId]);
  useEffect(() => { const item = catalog.find((x) => x.id === id); if (item) setDraft(createWorkflowWorkspaceDraft(item.config, draft?.view)); }, [catalog, id]); const current = catalog.find((x) => x.id === id); const running = insights?.analysis?.status === "running";
  async function save() { if (!draft || !id || draft.jsonError) return; setSaving(true); try { const updated = await updateWorkflow(id, { config: { stages: draft.stages, verifyAfter: draft.verifyAfter } }); setCatalog((items) => items.map((x) => x.id === updated.id ? updated : x)); setDraft(adoptServerConfig(draft, updated.config)); setMessage("Workflow guardado."); } catch (e) { setMessage((e as WorkflowSaveError).message); } finally { setSaving(false); } }
  async function create() { if (!newName.trim()) return setMessage("El nombre es obligatorio."); try { const item = await createWorkflow(newName.trim(), NEW_WORKFLOW_TEMPLATE); setCatalog((items) => [...items, item]); setId(item.id); setCreating(false); setNewName(""); } catch (e) { setMessage((e as Error).message); } }
  async function remove() { if (!current) return; try { await deleteWorkflow(current.id); setCatalog((items) => { const next = items.filter((x) => x.id !== current.id); setId(next[0]?.id ?? ""); return next; }); setDeleting(false); } catch (e) { const err = e as WorkflowSaveError; setMessage(err.code === "WORKFLOW_LAST" ? "no se puede eliminar el único workflow" : err.message); setDeleting(false); } }
  const actions = <><button className="n-btn n-btn-secondary" onClick={() => setCreating(true)}>＋ Nuevo</button><button className="n-btn n-btn-danger" disabled={catalog.length <= 1} onClick={() => setDeleting(true)}>Eliminar</button><button className="n-btn n-btn-secondary" onClick={() => setRangeOpen((open) => !open)}>✦ Analizar flujo reciente</button></>;
  const range = rangeOpen && <div className="ronin-analyze-range"><label>desde<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label>hasta<input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label><button className="n-btn n-btn-primary" disabled={!insights || !from || !to || from >= to || insights.busy || running} onClick={() => void insights?.start({ from: new Date(`${from}T00:00:00.000Z`).toISOString(), to: new Date(`${to}T23:59:59.999Z`).toISOString() })}>{running ? "Analizando…" : "Analizar"}</button></div>;
  const modals = <>{creating && <div className="ronin-inline-modal"><div><h2>Nuevo workflow</h2><label>Nombre<input value={newName} onChange={(e) => setNewName(e.target.value)} /></label><footer><button onClick={() => setCreating(false)}>Cancelar</button><button onClick={() => void create()}>Crear</button></footer></div></div>}{deleting && current && <div className="ronin-inline-modal"><div><h2>Eliminar workflow</h2><p>¿Eliminar <strong>{current.name}</strong>?</p><footer><button onClick={() => setDeleting(false)}>Cancelar</button><button onClick={() => void remove()}>Eliminar</button></footer></div></div>}</>;
  if (!draft || !current) return <div className="ronin-empty-workspace"><span>workflows</span><h1>{catalog.length ? "Cargando workflows…" : "Sin workflows"}</h1><div className="ronin-header-actions">{actions}</div>{range}{modals}</div>;
  const selectedStage = editingStage === null ? null : draft.stages[editingStage];
  return <div className="ronin-workflow-workspace"><header className="ronin-view-header"><div><select value={id} onChange={(e) => setId(e.target.value)}>{catalog.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><p><code>workflow.json · id inmutable {current.id}</code></p></div><div className="ronin-header-actions">{actions}<div className="ronin-segment">{(["graph", "stepper", "json"] as DraftView[]).map((x) => <button className={draft.view === x ? "active" : ""} key={x} onClick={() => setDraft(switchView(draft, x))}>{x === "graph" ? "Grafo" : x === "stepper" ? "Stepper" : "JSON"}</button>)}</div><button className="n-btn n-btn-primary" onClick={onLaunch}>▷ Lanzar</button></div></header>{range}<div className={`ronin-workflow-canvas ${draft.view === "graph" ? "graph" : ""}`}>{draft.view === "graph" && <WorkflowGraph stages={draft.stages} verifyAfter={draft.verifyAfter} onInsertStage={(index) => setDraft(setStages(draft, insertStageAt(draft.stages, index), draft.verifyAfter))} onStageClick={setEditingStage} />}{draft.view === "stepper" && <StageEditor stages={draft.stages} verifyAfter={draft.verifyAfter} allowVerifyCmd={false} onStages={(stages) => setDraft(setStages(draft, stages, draft.verifyAfter))} onVerifyAfter={(v) => setDraft(setStages(draft, draft.stages, v))} />}{draft.view === "json" && <WorkflowJsonEditor jsonText={draft.jsonText} jsonError={draft.jsonError} onChange={(text) => setDraft(setJsonText(draft, text))} />}</div><footer className="ronin-editor-footer">{message}<span className="ronin-footer-spacer" /><button onClick={() => setDraft(cancel(draft))}>Cancelar</button><button disabled={saving || Boolean(draft.jsonError)} onClick={() => void save()}>{saving ? "Guardando…" : "Guardar"}</button></footer>{modals}{selectedStage && editingStage !== null && <StageModal stage={selectedStage} allowVerifyCmd={false} onChange={(patch) => setDraft(setStages(draft, draft.stages.map((stage, index) => index === editingStage ? { ...stage, ...patch } : stage), draft.verifyAfter))} onClose={() => setEditingStage(null)} onDelete={() => { setDraft(setStages(draft, draft.stages.filter((_, index) => index !== editingStage), draft.verifyAfter)); setEditingStage(null); }} />}</div>;
}
export function WorkflowInspector({ insights, onAccepted }: { insights: WorkflowInsights; onAccepted: (id: string) => void }) { return <div className="ronin-inspector-inner"><span className="ronin-eyebrow">workflow</span><h2>Propuestas</h2><ProposalList proposals={insights.proposals} analysis={insights.analysis} busy={insights.busy} onAccept={(id) => void insights.accept(id).then((x) => x && onAccepted(x))} onDismiss={(id) => void insights.dismiss(id)} /></div>; }
