import { useMemo, useState } from "react";
import "./workflow-insights.css";
import { NewSessionDialog } from "./components/NewSessionDialog";
import { SessionPresentationDialog } from "./components/SessionPresentationDialog";
import { SessionContext } from "./components/sessions/SessionContext";
import { SessionInspector, SessionWorkspace } from "./components/sessions/SessionWorkspace";
import { useTmuxInventory } from "./components/sessions/useTmuxInventory";
import { SkillsContext, SkillsInspector, SkillsWorkspace } from "./components/skills/SkillsWorkspace";
import { WorkflowContext, WorkflowInspector, WorkflowWorkspace, useWorkflowInsights } from "./components/workflows/WorkflowWorkspace";
import { TestsScreen } from "./screens/TestsScreen";
import type { TmuxSessionInfo } from "./types";

type DesktopView = "sessions" | "terminals" | "workflows" | "tests" | "skills";
export function DesktopApp() {
  const [view, setView] = useState<DesktopView>("sessions"); const { sessions, diagnostic, selectedSession, setSelectedSession, refreshInventory } = useTmuxInventory(); const [filter, setFilter] = useState(""); const [newOpen, setNewOpen] = useState(false); const [presentation, setPresentation] = useState<TmuxSessionInfo | null>(null); const [acceptedWorkflowId, setAcceptedWorkflowId] = useState<string>(); const insights = useWorkflowInsights();
  const visible = useMemo(() => filter.trim() ? sessions.filter((x) => x.name.toLowerCase().includes(filter.trim().toLowerCase())) : sessions, [sessions, filter]); const current = sessions.find((x) => x.name === selectedSession) ?? null;
  return <div className="ronin-desktop nocturne"><div className="ronin-shell-body"><nav className="ronin-rail" aria-label="Navegación principal"><RailButton active={view === "sessions"} icon="▦" label="Sesiones" onClick={() => setView("sessions")} /><RailButton active={view === "terminals"} icon="⌨" label="Terminales" onClick={() => setView("terminals")} /><RailButton active={view === "workflows"} icon="⌘" label="Workflows" onClick={() => setView("workflows")} /><RailButton active={view === "tests"} icon="⚗" label="Pruebas" onClick={() => setView("tests")} /><RailButton active={view === "skills"} icon="▤" label="Skills" onClick={() => setView("skills")} /></nav><aside className="ronin-context-list">{(view === "sessions" || view === "terminals") && <SessionContext sessions={visible} selected={selectedSession} filter={filter} diagnostic={diagnostic} onFilter={setFilter} onSelect={setSelectedSession} onEditPresentation={setPresentation} onNew={() => setNewOpen(true)} />}{view === "workflows" && <WorkflowContext />}{view === "skills" && <SkillsContext />}</aside><main className="ronin-workspace">{(view === "sessions" || view === "terminals") && <SessionWorkspace session={current} diagnostic={diagnostic} terminalGrid={view === "terminals"} onRefresh={refreshInventory} onNew={() => setNewOpen(true)} />}{view === "workflows" && <WorkflowWorkspace insights={insights} selectId={acceptedWorkflowId} onLaunch={() => setNewOpen(true)} />}{view === "skills" && <SkillsWorkspace />}{view === "tests" && <TestsScreen />}</main><aside className="ronin-inspector">{(view === "sessions" || view === "terminals") && <SessionInspector session={current} diagnostic={diagnostic} />}{view === "workflows" && <WorkflowInspector insights={insights} onAccepted={setAcceptedWorkflowId} />}{view === "skills" && <SkillsInspector />}</aside></div><footer className="ronin-statusbar"><span className="ronin-mark" /><strong>Ronin</strong><span className="ronin-title-context">{current?.presentation?.title || current?.name || "sin sesión"}</span><span className="ronin-title-spacer" /><span className={`ronin-health ${diagnostic ? "error" : ""}`}>{diagnostic ? diagnostic.code : "tmux listo"}</span></footer>{newOpen && <NewSessionDialog onClose={() => setNewOpen(false)} onCreated={(name) => { setSelectedSession(name); void refreshInventory(); }} />}{presentation && <SessionPresentationDialog session={presentation} onCancel={() => setPresentation(null)} onSaved={() => { setPresentation(null); void refreshInventory(); }} />}</div>;
}
function RailButton({ active, icon, label, onClick }: { active?: boolean; icon: string; label: string; onClick: () => void }) { return <button className={`ronin-rail-button ${active ? "active" : ""}`} title={label} aria-label={label} onClick={onClick}>{icon}</button>; }
